name: Build and deploy container image - only from main branch and pull requests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

env:
  CONTAINER_REGISTRY_URL: docker.io
  CONTAINER_REGISTRY_USERNAME: kamranazeem
  CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
  CONTAINER_IMAGE_NAME: helloworld
  SITE_NAME: basic-cd.demo.wbitt.com
  SITE_ID: basic-cd-demo-wbitt-com
  NAMESPACE: default
  DEPLOYMENT_TEMPLATE_FILE: dep-svc-ing-http.template.yaml
  # Use the following only "if" you have ingress controller in your
  #   kubernetes cluster and SSL certificate ACME is functional too.
  # DEPLOYMENT_TEMPLATE_FILE: dep-svc-ing-https.template.yaml
  
jobs:
  publish-container-image:
    runs-on: ubuntu-latest
    steps:

    - name: checkout source code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log-into-Container-Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_URL }}
        username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}


     - name: Build and push container image
      id: build-and-push-container-image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${GITHUB_SHA},latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

 
  deploy-application-to-k8s:
    needs: [publish-container-image]
    runs-on: ubuntu-latest
    steps:

    - uses: actions-hub/kubectl@master
      env:
        # the secrets file need to be in base64 format.
        KUBE_CONFIG: ${{ secrets.KUBECONFIG_FILE }}
      with:
        args: -n ${NAMESPACE} get pods


    #~ - name: Export kustomize
      #~ working-directory: ./ent/kustomize
      #~ run: |
        #~ export CONTAINER_REGISTRY_URL CONTAINER_REGISTRY_PROJECT_NAME CONTAINER_IMAGE_NAME  CONTAINER_IMAGE_TAG
        #~ kustomize build overlays/dev | envsubst > ../../ent-gitops/application-resources/dev/main.yaml

 
