---
name: Build and deploy container image - only from main branch and pull requests
on:
  push:
    branches:
      - main
      - master
  pull_request: null

env:
  CONTAINER_REGISTRY_URL: docker.io
  CONTAINER_REGISTRY_USERNAME: kamranazeem
  CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
  CONTAINER_IMAGE_NAME: helloworld
  SITE_NAME: basic-cd.demo.wbitt.com
  SITE_ID: basic-cd-demo-wbitt-com
  NAMESPACE: default
  DEPLOYMENT_TEMPLATE_FILE: dep-svc-ing-http.template.yaml

jobs:
  publish-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log-into-Container-Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Build and push container image
        id: build-and-push-container-image
        uses: docker/build-push-action@v5
        with:
          context: .
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          push: true
          tags: "${{ env.CONTAINER_REGISTRY_URL }}/${{ env.CONTAINER_REGISTRY_USERNAME }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  deploy-application-to-k8s:
    needs:
      - publish-container-image
    runs-on: ubuntu-latest
    container:
      image: wbitt/gcp-tools
    steps:
      - name: make directory
        run: mkdir ${HOME}/.kube
      - name: create kubeconfig file
        run: cat ${{ secrets.KUBECONFIG_FILE }} > ${HOME}/.kube/config
      - name: replace variables with values in the template file
        run: |
          sed \
            -e s/CONTAINER_REGISTRY_URL/${{ env.CONTAINER_REGISTRY_URL }}/ \
            -e s/CONTAINER_REGISTRY_USER/${{ env.CONTAINER_REGISTRY_USERNAME }}/ \
            -e s/CONTAINER_IMAGE_NAME/${{ env.CONTAINER_IMAGE_NAME }}/ \
            -e s/IMAGE_TAG/${{ github.sha }}/ \
            -e s/SITE_NAME/${{ env.SITE_NAME }}/ \
            -e s/SITE_ID/${{ env.SITE_ID }}/ \
            ${DEPLOYMENT_TEMPLATE_FILE} > /tmp/dep-svc-ing.yaml
      - run: cat /tmp/dep-svc-ing.yaml
      - run: |
          kubectl -n ${NAMESPACE} delete -f /tmp/dep-svc-ing.yaml || true
          sleep 3
          kubectl -n ${NAMESPACE} apply -f /tmp/dep-svc-ing.yaml


# Note: run: |    is for multiple independent lines, like a script.
#       run: >    is for a single multi-line command , like sed above.
# https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines

################################################################
# The following code is simple, but works.

  #~ deploy-application-to-k8s:
    #~ needs:
      #~ - publish-container-image
    #~ runs-on: ubuntu-latest
    #~ steps:
      #~ - uses: actions-hub/kubectl@master
        #~ env:
          #~ KUBE_CONFIG: ${{ secrets.KUBECONFIG_FILE }}
        #~ with:
          #~ args: -n ${{ env.NAMESPACE }} get pods
